### ISSUE TITLE
Custom pagination

### ISSUE THREAD

**Issue by matyushen** [glueckpress/flexslider-native-gallery#1]
Hi there! Great plugin! 
I was trying to add custom pagination like discussed here https://github.com/woothemes/FlexSlider/issues/425
This method didn't work for me, maybe it need some adjustments or I'm doing something wrong? Do you have any thoughts how to do this? Thanks!

**Comment by glueckpress** [comment]
Appreciate the question, but unfortunately have no resources looking into it in the near future. Please feel free to fork and find out! :)
